<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333333; margin: 0; padding: 0; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eeeeee; border-radius: 8px; }
        .header { border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; color: #111827; margin: 0; }
        .subtitle { font-size: 14px; color: #6b7280; margin-top: 4px; }
        .brief { background-color: #f5f7ff; border-left: 4px solid #6366f1; padding: 15px; font-style: italic; margin-bottom: 25px; }
        .section-title { font-size: 18px; font-weight: bold; margin-bottom: 15px; color: #111827; }
        .task-list { margin-bottom: 25px; }
        .task-item { padding: 15px; border: 1px solid #e5e7eb; border-radius: 6px; margin-bottom: 10px; }
        .task-header { display: flex; justify-content: space-between; align-items: flex-start; }
        .task-name { font-weight: bold; color: #111827; margin: 0; }
        .task-hours { background-color: #eef2ff; color: #4338ca; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
        .task-desc { font-size: 13px; color: #4b5563; margin-top: 5px; }
        .summary-card { background-color: #111827; color: #ffffff; padding: 25px; border-radius: 12px; }
        .summary-title { font-size: 16px; font-weight: bold; border-bottom: 1px solid #374151; padding-bottom: 10px; margin-bottom: 15px; }
        .summary-row { display: flex; justify-content: space-between; margin-bottom: 10px; font-size: 14px; }
        .summary-label { color: #9ca3af; }
        .summary-total-label { font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.05em; color: #818cf8; margin-bottom: 5px; }
        .summary-total-value { font-size: 28px; font-weight: 800; }
        .footer { text-align: center; font-size: 11px; color: #9ca3af; margin-top: 30px; border-top: 1px solid #eeeeee; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 class="title">Project Estimate</h1>
            <div class="subtitle">Prepared by {{ $estimate->user->name }} &bull; {{ $estimate->created_at->format('F d, Y') }}</div>
        </div>

        <div class="brief">
            <strong>Project Brief:</strong><br>
            "{{ $estimate->brief }}"
        </div>

        <div class="section-title">Task Breakdown</div>
        <div class="task-list">
            @foreach ($estimate->tasks ?? [] as $task)
            <div class="task-item">
                <div class="task-header">
                    <span class="task-name">{{ $task['name'] }}</span>
                    <span class="task-hours">{{ $task['hours'] }} hrs</span>
                </div>
                <div class="task-desc">{{ $task['description'] }}</div>
            </div>
            @endforeach
        </div>

        <div class="summary-card">
            <div class="summary-title">Estimate Summary</div>
            <div class="summary-row">
                <span class="summary-label">Total Resource Time</span>
                <span style="font-weight: bold;">{{ number_format($estimate->total_hours, 1) }} hrs</span>
            </div>
            <div class="summary-row">
                <span class="summary-label">Standard Billable Rate</span>
                <span style="font-weight: bold;">{{ number_format($estimate->hourly_rate > 0 ? $estimate->hourly_rate : ($estimate->user->hourly_rate ?? 45), 2) }} {{ $estimate->currency }}</span>
            </div>
            <div style="margin-top: 20px; border-top: 1px solid #374151; padding-top: 15px;">
                <div class="summary-total-label">Estimated Total project cost</div>
                <div class="summary-total-value">{{ $estimate->currency }} {{ number_format($estimate->price_low) }} – {{ number_format($estimate->price_high) }}</div>
            </div>
        </div>

        <div class="footer">
            Generated by {{ config('app.name') }} &bull; Professional Freelance Tools
        </div>
    </div>
</body>
</html>
